name: CI/CD Pipeline

on:
  push:
    branches:
      - feature 

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update staging
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install zappa Flask requests boto3
          zappa update staging 

      - name: Init game
        run: |
          curl -s --fail https://papfg85frk.execute-api.eu-west-2.amazonaws.com/staging/ > /dev/null

      - name: Test move with retries
        run: |
          for i in {1..5}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" \
              -X POST -H "Content-Type: application/json" \
              -d '{"move": "1"}' \
              https://papfg85frk.execute-api.eu-west-2.amazonaws.com/staging/move)
            [ "$status" -eq 200 ] && break
            sleep 5
          done
          [ "$status" -eq 200 ] || exit 1

  promote-to-dev:
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Merge game.py from staging to main
        run: |
          git config --global user.name "klio-24"
          git config --global user.email "klioballiu4@gmail.com"

          git fetch origin
          git checkout main
          git checkout feature -- app.py
          git commit -m "Promote game.py from staging to main"
          git push origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update dev
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install zappa Flask requests boto3
          zappa update dev 